swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /connection:
    post:
      operationId: "connection.submit"
      tags:
        - "Submit"
      summary: "Submit creditential"
      description: "send the creditential to the back end"
      parameters:
        - name: pseudo
          in: query
          description: pseudo of user
          required: True
          type: string
        - name: password
          in: query
          description: password of user
          required: True
          type: string
      responses:
        200:
          description: "Submit successfuly"